# Generated by Django 2.2.7 on 2019-11-05 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_auto_20191104_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 9, 5, 41, 151175, tzinfo=utc)),
        ),
    ]
